# Generated by Django 5.2.6 on 2025-09-28 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structureApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structure',
            old_name='defintion',
            new_name='definition',
        ),
    ]
