# Generated by Django 5.2.6 on 2025-09-28 13:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structureApp', '0002_rename_defintion_structure_definition'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueStructure',
            fields=[
                ('id_historique', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_structure', models.UUIDField(null=True)),
                ('action', models.CharField(max_length=200)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('id_utilisateur', models.UUIDField()),
                ('note', models.CharField(max_length=255, null=True)),
                ('nom', models.CharField(max_length=100)),
                ('definition', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
